
tarea1a: brazo_robotico.c
	gcc brazo_robotico.c -o tarea1a -g

tarea1b: brazo_robotico.cpp
	gcc brazo_robotico.cpp -o tarea1b -g

tarea2a: reduciendo_digitos.c
	gcc reduciendo_digitos.c -o tarea2a -g

tarea2b: reduciendo_digitos.cpp
	gcc reduciendo_digitos.cpp -o tarea2b -g

