
1: 1_multiples_sum.c
	gcc -Wall 1_multiples_sum.c -o 1 -O2

2: 2_even_fibonacci.c
	gcc -Wall 2_even_fibonacci.c -o 2 -O2

3: 3_largest_prime_factor.c
	gcc -Wall 3_largest_prime_factor.c -o 3 -lm -O2

4: 4_largest_palindrome.c
	gcc -Wall 4_largest_palindrome.c -o 4 -O2

5: 5_smallest_multiple.c
	gcc -Wall 5_smallest_multiple.c -o 5 -O2

6: 6_sum_square_dif.c
	gcc -Wall 6_sum_square_dif.c -o 6 -O2

7: 7_10001st_prime.c
	gcc -Wall 7_10001st_prime.c -o 7 -O2

8: 8_largest_product_series.c
	gcc -Wall 8_largest_product_series.c -o 8 -O2

9: 9_special_pytha_triple.c
	gcc -Wall 9_special_pytha_triple.c -o 9 -lm -O2

10: 10_summation_of_primes.c
	gcc -Wall 10_summation_of_primes.c -o 10 -lm -O2

11: 11_largest_product_grid.c
	gcc -Wall 11_largest_product_grid.c -o 11 -O2

12: 12_divisible_triangular_number.c
	gcc -Wall 12 12_divisible_triangular_number.c -o 12 -O2
