
weird_algo: weird_algorithm.cpp
	g++ -std=c++11 -O2 -Wall weird_algorithm.cpp -o weird_algo

missigno: missing_number.cpp
	g++ -std=c++11 -O2 -Wall missing_number.cpp -o missigno

repe: repetition.cpp
	g++ -std=c++11 -O2 -Wall repetition.cpp -o repe

array: increasing_array.cpp
	g++ -std=c++11 -O2 -Wall increasing_array.cpp -o array

